name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:
  page_build:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-pdf-export-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mknotebooks
      - run: pip install mkdocs-video
      - run: mkdocs gh-deploy --force
